#
# Copyright 2022 John C. Feltz, github: Feltz-UD-EE/garden_1
#
# Loads Raspberry Pi pinouts
#

Pin.create(number: 1, description: "3v3 Power", gpio: nil)
Pin.create(number: 2, description: "5v Power", gpio: nil)
Pin.create(number: 3, description: "I2C1 SDA", gpio: 2)
Pin.create(number: 4, description: "5v Power", gpio: nil)
Pin.create(number: 5, description: "I2C1 SCL", gpio: 3)
Pin.create(number: 6, description: "Ground", gpio: nil)
Pin.create(number: 7, description: "GPCLK0", gpio: 4)
Pin.create(number: 8, description: "UART TX", gpio: 14)
Pin.create(number: 9, description: "Ground", gpio: nil)
Pin.create(number: 10, description: "UART RX", gpio: 15)
Pin.create(number: 11, description: "", gpio: 17)
Pin.create(number: 12, description: "PCM CLK", gpio: 18)
Pin.create(number: 13, description: "", gpio: 27)
Pin.create(number: 14, description: "Ground", gpio: nil)
Pin.create(number: 15, description: "", gpio: 22)
Pin.create(number: 16, description: "", gpio: 23)
Pin.create(number: 17, description: "3v3 Power", gpio: nil)
Pin.create(number: 18, description: "", gpio: 24)
Pin.create(number: 19, description: "SPI0 MOSI", gpio: 10)
Pin.create(number: 20, description: "Ground", gpio: nil)
Pin.create(number: 21, description: "SPI0 MISO", gpio: 9)
Pin.create(number: 22, description: "", gpio: 25)
Pin.create(number: 23, description: "SPI0 SCLK", gpio: 11)
Pin.create(number: 24, description: "SPI0 CE0", gpio: 8)
Pin.create(number: 25, description: "Ground", gpio: nil)
Pin.create(number: 26, description: "SPI0 CE1", gpio: 7)
Pin.create(number: 27, description: "EEPROM SDA", gpio: 0)
Pin.create(number: 28, description: "EEPROM SCL", gpio: 1)
Pin.create(number: 29, description: "", gpio: 5)
Pin.create(number: 30, description: "Ground", gpio: nil)
Pin.create(number: 31, description: "", gpio: 6)
Pin.create(number: 32, description: "PMW0", gpio: 12)
Pin.create(number: 33, description: "PMW1", gpio: 13)
Pin.create(number: 34, description: "Ground", gpio: nil)
Pin.create(number: 35, description: "PCM FS", gpio: 19)
Pin.create(number: 36, description: "", gpio: 16)
Pin.create(number: 37, description: "", gpio: 26)
Pin.create(number: 38, description: "PCM DIN", gpio: 20)
Pin.create(number: 39, description: "Ground", gpio: nil)
Pin.create(number: 40, description: "PCMDOUT", gpio: 21)
